//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Core.Resources.SharedResources.de", typeof(SharedResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hinzufügen.
        /// </summary>
        internal static string Action_Add {
            get {
                return ResourceManager.GetString("Action.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} erstellen.
        /// </summary>
        internal static string Action_Create {
            get {
                return ResourceManager.GetString("Action.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} löschen.
        /// </summary>
        internal static string Action_Delete {
            get {
                return ResourceManager.GetString("Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bearbeiten.
        /// </summary>
        internal static string Action_Edit {
            get {
                return ResourceManager.GetString("Action.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurück.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbrechen.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schließen.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to löschen.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nein.
        /// </summary>
        internal static string Button_No {
            get {
                return ResourceManager.GetString("Button.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speichern.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; darf nicht leer sein..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
    }
}
