//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Core.NumberSequences.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberSequenceResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberSequenceResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Core.NumberSequences.Resources.NumberSequenceResources.de", typeof(NumberSequenceResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Field_Name {
            get {
                return ResourceManager.GetString("Field.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächster Wert.
        /// </summary>
        internal static string Field_NextNumber {
            get {
                return ResourceManager.GetString("Field.NextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestlänge.
        /// </summary>
        internal static string Field_NumberLength {
            get {
                return ResourceManager.GetString("Field.NumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kürzel.
        /// </summary>
        internal static string Field_Prefix {
            get {
                return ResourceManager.GetString("Field.Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der nächste Wert muss größer 0 sein..
        /// </summary>
        internal static string Validation_NextNumber {
            get {
                return ResourceManager.GetString("Validation.NextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Mindestlänge muss zwischen 1 und 6 sein..
        /// </summary>
        internal static string Validation_NumberLength {
            get {
                return ResourceManager.GetString("Validation.NumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kürzel darf aus max. 2 Zeichen bestehen..
        /// </summary>
        internal static string Validation_Prefix {
            get {
                return ResourceManager.GetString("Validation.Prefix", resourceCulture);
            }
        }
    }
}
