//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Core.Jobs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Core.Jobs.Resources.JobResources.de", typeof(JobResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe ausführen.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufgabe wurde erfolgreich gestartet..
        /// </summary>
        internal static string ExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Field_Description {
            get {
                return ResourceManager.GetString("Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beendet.
        /// </summary>
        internal static string Field_FinishedAt {
            get {
                return ResourceManager.GetString("Field.FinishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Field_Name {
            get {
                return ResourceManager.GetString("Field.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Field_ParamJson {
            get {
                return ResourceManager.GetString("Field.ParamJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgelöst.
        /// </summary>
        internal static string Field_QueuedAt {
            get {
                return ResourceManager.GetString("Field.QueuedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestartet.
        /// </summary>
        internal static string Field_StartedAt {
            get {
                return ResourceManager.GetString("Field.StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Field_Status {
            get {
                return ResourceManager.GetString("Field.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgelöst von.
        /// </summary>
        internal static string Field_TriggeredBy {
            get {
                return ResourceManager.GetString("Field.TriggeredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Ausführung.
        /// </summary>
        internal static string LatestStarted {
            get {
                return ResourceManager.GetString("LatestStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Status.
        /// </summary>
        internal static string LatestStatus {
            get {
                return ResourceManager.GetString("LatestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusmeldung.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufgabe wurde noch nicht ausgeführt..
        /// </summary>
        internal static string NoRuns {
            get {
                return ResourceManager.GetString("NoRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgebrochen.
        /// </summary>
        internal static string Status_Canceled {
            get {
                return ResourceManager.GetString("Status.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlgeschlagen.
        /// </summary>
        internal static string Status_Failed {
            get {
                return ResourceManager.GetString("Status.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartend.
        /// </summary>
        internal static string Status_Queued {
            get {
                return ResourceManager.GetString("Status.Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführung.
        /// </summary>
        internal static string Status_Running {
            get {
                return ResourceManager.GetString("Status.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich.
        /// </summary>
        internal static string Status_Succeeded {
            get {
                return ResourceManager.GetString("Status.Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status aktualisieren.
        /// </summary>
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
    }
}
